### ISSUE TITLE
Adding Unity instance crashes Companion (v1.4 and v2.0) on Windows

### ISSUE THREAD

**Issue by LLDshooper** [bitfocus/companion-module-audivero-unityintercom#2]
When adding the Unity Instance on Companion for windows, Companion crashes completely and restarts with no other instances in the list, even if they were there previsouly.

Occurs in the latest build of v1.4 and v2.0 on Windows 10.

Cheers,
Sean

**Comment by josephdadams** [comment]
Do you get any error messages?

**Comment by josephdadams** [comment]
@LLDshooper feel free to post a screenshot of any error messages so we can try to debug this together. I’ll close the issue until I hear from you again.
