### ISSUE TITLE
Is it possible to have two different instances from different IPs?

### ISSUE THREAD

**Issue by ghost** [bitfocus/companion-module-audivero-unityintercom#4]
I am trying to control unity from two different computers on the same Companion interface. Despite the IPs working individualy, they dont seem to be functioning together. I always get the error `Network error: bind EADDRINUSE 0.0.0.0:20119`, on the second one, meaning that the the port is not available. Is there a way around this problem, or should I try and find something else?

**Comment by josephdadams** [comment]
I suspect you intended to post this in the `audivero-unityintercom-client` repo as this is a client problem. See this issue as I believe it describes why you cannot control unity from two different computers from the same Companion interface. It is a shortcoming of Unity's protocol, not something Companion can fix: https://github.com/bitfocus/companion-module-audivero-unityintercom-client/issues/7
