### ISSUE TITLE
Module not available in Companion

### ISSUE THREAD

**Issue by cpuguru07** [bitfocus/companion-module-audivero-unityintercom#5]
This module does not seem to be available (at least in Companion v3.1.0+6170). Only the Audivero: Unity Intercom Client module is available.

**Comment by jeremyrmck** [comment]
Can confirm, I don't see it as an option to add in companion. @josephdadams are you able to help?

**Comment by josephdadams** [comment]
It literally only tells you if a user is logged in and nothing else. But if you would like it updated for companion v3 and added, send me an email (my email is on my Github profile) and we can discuss my pricing.
